server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:../easyblog.db
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect

jwt:
  secret: easyblogSecretKey2023
  expiration: 86400
